### PR TITLE
Add multiple LabVIEW instances support

### PR DESCRIPTION
**Pull request by Zieleslaw**
Solves #96

### CODE REVIEW

**Comment by JamesMc86** [comment]
The concept looks good. The main issue is that the source code needs to be kept in 2011 but I think this is a more recent version. Are you able to save it back?

Then I'll do some testing against it but I don't see there should be any particular issue.

**Comment by Zieleslaw** [comment]
Sure, now it's in LV 11.0.

**Comment by JamesMc86** [comment]
Hi Zielslaw,

I just did some testing and there are a couple of problems that need fixing.

1. The TCP connection isn't wired through.
2. Even with that wired this doesn't work if used in an EXE. I guess this is because it can't find LabVIEW ini.

I would suggest putting the multiple instances check inside a run time engine conditional disable instead.

To verify it is working:

1. Build and install the vip file locally.
2. Under "Integration Tests" open the lvproj and build all the exes.
3. Run the batch file in the "integration tests" folder

This should run to completion if everything is working.

The good news is the VI based tests seem to work in multiple instance mode or not so the change is good in the IDE.

Any trouble I can work on this again next week. but got to pack up for the day now.

**Comment by Zieleslaw** [comment]
Hi James,
It's weird that I missed connecting this wire. Already corrected.
"VI library" function returns application directory when used in an exe, so you're right. I rebuilt this code fragment, integration tests pass.
Let me know if there is anything left to correct.

**Comment by JamesMc86** [comment]
Awesome looks great - theres a bug fix to go out too so I hope to release this in the next week or two.

**Comment by Zieleslaw** [comment]
> 
> 
> Awesome looks great - theres a bug fix to go out too so I hope to release this in the next week or two.

Hi James,
we would be really grateful if you could release a new version with this feature, as we're updating our CI environment. 
Will it be possible anytime soon?
Thanks in advance!

**Comment by JamesMc86** [comment]
Yes, sorry I got sidetracked on other changes. I'm kicking off the process now

**Pull request merged**
